### ISSUE TITLE
Make catkin_ws/src a Docker volume

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#37]
### Purpose
Make the ROS 1 workspace persistent so that uncommitted changes survive rebuilds.

### Resources
- https://code.visualstudio.com/remote/advancedcontainers/add-local-file-mount
- Volumes that are currently set up in the dev image and devcontainer.json: bash history and ros logs

**Comment by patrick-5546** [comment]
Test if this works across dev images

**Comment by DFriend01** [comment]
@Harvir14 If we clone our repositories in the [dev container image](https://github.com/UBCSailbot/sailbot_workspace/blob/main/.devcontainer/dev/Dockerfile), we could potentially lose work when updating the image and rebuilding the container.

Rather than cloning during the build process, we should just write a script that checks if the directory is cloned, and if it is not, then the directory is cloned. Otherwise, we do not clone it.

Write a script for the ROS1 workspace (`/workspaces/catkin_ws/src/`) and for the ROS2 workspace (`/workspaces/sailbot_workspace/src/`). Then, we would want to remove the lines below and build the image again:

https://github.com/UBCSailbot/sailbot_workspace/blob/4b35bea3e1b8de4e2c03f25dadaece7748791947/.devcontainer/dev/Dockerfile#L105-L107

@patrick-5546 Does this sound about right?

**Comment by patrick-5546** [comment]
Yes, but this would only be necessary if the current method doesn't work. See if the current method persists across dev images first.

**Comment by Harvir14** [comment]
Devon and I confirmed that the issue does not exist when you pull and build a different Dev Image from Github, so we can close this issue.
